apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - auth_proxy_service.yaml
  - auth_proxy_role.yaml
  - auth_proxy_role_binding.yaml
  - auth_proxy_client_clusterrole.yaml
patches:
  - path: manager_auth_proxy_patch.yaml
